# Generated by Django 5.0.3 on 2024-03-17 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='num_tickets',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
