# Generated by Django 5.0.3 on 2024-03-27 14:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telegram_url',
            field=models.CharField(max_length=32, validators=[django.core.validators.RegexValidator(message='Telegram URL должен начинаться\'\n                                                                                с символа "@" и содержать только буквы,\n                                                                                цифры и символ "_"', regex='^@[\\w\\d_]*$')]),
        ),
    ]
